id: A02D09CDE
base_file: f688B.txt
type: translation
source_metadata:
  languages:
  - en
  - de
  - es
  - fr
  - bo
  datatype: PlainText
  created_at: 2022-05-30 22:49:55.271060
  last_modified_at: 2022-05-30 22:49:55.271067
