id: A02D09CDE
base_file: f93A9.txt
type: translation
source_metadata:
  languages:
  - en
  - fr
  - bo
  datatype: PlainText
  created_at: 2022-05-30 22:49:55.279636
  last_modified_at: 2022-05-30 22:49:55.279641
