id: A02D09CDE
base_file: f2D7C.txt
type: translation
source_metadata:
  languages:
  - en
  - es
  - fr
  - bo
  datatype: PlainText
  created_at: 2022-05-30 22:49:55.246466
  last_modified_at: 2022-05-30 22:49:55.246474
