id: A02D09CDE
base_file: f3CDD.txt
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-05-30 22:49:55.249111
  last_modified_at: 2022-05-30 22:49:55.249120
