id: A02D09CDE
base_file: fDAA8.txt
type: translation
source_metadata:
  languages:
  - en
  - pt
  - bo
  datatype: PlainText
  created_at: 2022-05-30 22:49:55.284740
  last_modified_at: 2022-05-30 22:49:55.284743
