id: A02D09CDE
base_file: f6156.txt
type: translation
source_metadata:
  languages:
  - en
  - es
  - fr
  - bo
  datatype: PlainText
  created_at: 2022-05-30 22:49:55.267258
  last_modified_at: 2022-05-30 22:49:55.267277
